# This is a basic workflow to help you get started with Actions

name: Web App Build & Test

# Controls when the workflow will run
on: [push, pull_request]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-app
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.11"]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Digital Ocean deployment
      - name: Build image 
        run: docker compose up -d
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600
      - name: Tag image 
        run: docker tag final-project-team3-final-web-app registry.digitalocean.com/swefinalteam3/image
      - name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/swefinalteam3/image
      # Runs a set of commands using the runners shell
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest
